/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "teste_integer.v:25" *)
module teste_integer(val_in, val_out);
  (* src = "teste_integer.v:26" *)
  input [31:0] val_in;
  (* src = "teste_integer.v:27" *)
  output [31:0] val_out;
  assign val_out = val_in + (* src = "teste_integer.v:36" *) 4'ha;
endmodule
