/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "teste_clock.v:25" *)
module teste_clock(clk, reset, count);
  (* src = "teste_clock.v:36" *)
  wire [7:0] _0_;
  (* src = "teste_clock.v:26" *)
  input clk;
  (* src = "teste_clock.v:28" *)
  output [7:0] count;
  (* init = 8'h00 *)
  (* src = "teste_clock.v:34" *)
  reg [7:0] reg_count = 8'h00;
  (* src = "teste_clock.v:27" *)
  input reset;
  assign _0_ = reg_count + (* src = "teste_clock.v:40" *) 1'h1;
  always @(posedge clk or posedge reset)
    if (reset)
      reg_count <= 8'h00;
    else
      reg_count <= _0_;
  assign count = reg_count;
endmodule
